export const TOGGLE_THEME = "TOGGLE_THEME";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const TOGGLE_MEDIA_TYPE = "TOGGLE_MEDIA_TYPE";
